### ISSUE TITLE
How to handle preview for layers that only have a ZIP download link

### ISSUE THREAD

**Issue by krdyke** [borchert/OGP2#1]
For example, for all of the Hennepin County datasets, we only have ZIP files, but we link directly to them. Currently it seems that if the location field looks like this:

```
{"download": "http://gis-stage.hennepin.us/publicgisdata/HealthPacket.zip"}
```

Then the record in OGP shows up with a checkbox in preview. Click on the preview checkbox and you get a blank popup. The question is how should we handle this? I'd prefer to eliminate the preview checkbox for these cases, which seems like it ought to be fairly simple to implement (or maybe there's something not quite right with our metadata?)

![screen shot 2015-01-28 at 4 34 30 pm](https://cloud.githubusercontent.com/assets/666141/5948586/a02aa394-a70b-11e4-9ad7-4a59ce5ae603.png)

**Comment by cheetah90** [comment]
Hi Kevin,
I'll check this this afternoon and hopefully I can figure it out.

**Comment by cheetah90** [comment]
Hi Kevin,

How's this issue going? I can't remember if we've solved it yet....

**Comment by krdyke** [comment]
Nothing's different from what I originally posted. Did you look into it?

**Comment by krdyke** [comment]
see pull request #2

**Comment by cheetah90** [comment]
I'll close this issue.
