### ISSUE TITLE
ISO 19139 metadata not being parsed

### ISSUE THREAD

**Issue by krdyke** [borchert/OGP2#3]
If you click on the metadata button for a layer using the ISO19139 standard, a Metadata Type exception gets thrown. I can't find what's wrong. The problem is in MetadataFromSolr.java, the getMetadataType function.

Try searching for layer "Police Incidents 2010" to see it in action.

http://54.235.211.28:8080/solr/collection1/select?q=LayerId%3A83f5ee7a4ee14c66b4d002bd21e06d67_0&wt=json&indent=true

@cheetah90 Can you take a look at this? I'd like to start converting all of our metadata into ISO, but need to have this figured out prior to the switch. Thanks!

**Comment by cheetah90** [comment]
Kevin,
Can you provide me with a specific layer that trigger the problem? I am going to fix this problem. Basically, I see from the Java source code that only FGDC parsing machinery are written. 

Thanks,
Allen

**Comment by krdyke** [comment]
Layer with the display name "Police Incidents 2010" and id "83f5ee7a4ee14c66b4d002bd21e06d67_0"

Additionally, anything with publisher of City of Minneapolis or Hennepin County.

**Comment by krdyke** [comment]
There's at least **something** for parsing ISO metadata, as you can see here

https://github.com/cheetah90/OGP2/blob/fcf274b418a03ac4caffca581be2259a60f5cd1e/geoportal_1/src/main/java/org/opengeoportal/download/MetadataFromSolr.java#L258

**Comment by krdyke** [comment]
Any news on this issue?

**Comment by cheetah90** [comment]
Unfortunately no. I am on mid-term exam week this week. Will work on this
this on Thursday.

Sorry about that!
Allen

On Tue, Mar 10, 2015 at 10:47 AM, Kevin Dyke notifications@github.com
wrote:

> Any news on this issue?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/cheetah90/OGP2/issues/3#issuecomment-78081882.

## 

林轶伦 LIN, Yilun (Allen)

**Comment by cheetah90** [comment]
Problem fixed. DocumentBuilderFactory need to be set to namespace-awared. http://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/DocumentBuilderFactory.html#setNamespaceAware(boolean)
